#!/bin/sh

tokaido_install_package()
{
  typeset _lib
  _lib=$1
  includes ${_lib}
  package is installed ${_lib} &&
    log step "${_lib} already installed" true ||
    package install name ${_lib} static
  package reset
}

tokaidoapp_install_dependencies()
{
  typeset _set _lib

  for _set in libraries
  do
    set_install ${_set}
  done

  tokaido_install_package libyaml
  tokaido_install_package zlib
  tokaido_install_package openssl version 0.9.8t
}

tokaidoapp_prefetch()
{
  package define \
    file "ruby-${package_version}.${archive_format}" \
    dir  "ruby-${package_version}"
}
