#!/bin/sh

tokaido_install_package()
{
  includes $1
  package is installed $1 &&
    log step "$1 already installed" true ||
    package install name $@ static
  package reset
}

tokaidoapp_install_dependencies()
{
  typeset _set _lib

  for _set in libraries
  do
    set_install ${_set}
  done

  tokaido_install_package libyaml
  tokaido_install_package zlib
  if os is darwin
  then
    # TODO: why limit openssl on osx ?
    tokaido_install_package openssl version 0.9.8t
  else
    tokaido_install_package openssl
  fi
}

tokaidoapp_prefetch()
{
  package define \
    file "ruby-${package_version}.${archive_format}" \
    dir  "ruby-${package_version}"
}

tokaidoapp_preconfigure()
{
  # only on osx, on linux it causes glibc conflicts
  if os is darwin
  then
    LDFLAGS="-Bstatic $LDFLAGS"
  else
    LDFLAGS="-static $LDFLAGS"
  fi
}
